Optimisation
fabientownsend/elixir_tictactoe pull request #1
Opened 2017-04-10 16:21 UTC by fabientownsend

2017-04-10 17:03 UTC, felipesere requested changes

2017-04-10 17:03 UTC, felipesere commented on lib/computer.ex
> +    Enum.take_random([0, 2, 4, 6, 8], 1) |> Enum.at(0)
This can be simplified with https://hexdocs.pm/elixir/Enum.html#random/1

2017-04-10 17:03 UTC, felipesere commented on lib/computer.ex
> +    |> Enum.max_by(fn(move) -> elem(move, 1) end)
this cold be `Enum.max_by(fn {_, move}) ->move)`

2017-04-10 17:03 UTC, felipesere commented on lib/computer.ex
> +  defp minimizing_player(board, mark, depth, alpha, beta) do
This duplication is pretty narly. Maybe you can extract the differences into a function that you pass in?

2017-04-10 17:03 UTC, felipesere commented on lib/computer.ex
> +      fn(position) ->
I don't think this reads particularly well...
position
|> Enum.map(...)

And then see if you can shrink that function? `false` and `9` seem to be constants!

2017-04-11 09:03 UTC, fabientownsend commented on lib/computer.ex
> +      fn(position) ->
About the 9,  the computer is really tied to a 3*3 board at the moment. 

Then random move isn't really random as it's the best opening move for a 3*3, I don't really know how to make it scale other by really randomise if the board is over 3*3.

2017-04-11 09:03 UTC, fabientownsend commented on lib/computer.ex
> +    |> Enum.max_by(fn(move) -> elem(move, 1) end)
Look nice

2017-04-11 09:03 UTC, fabientownsend commented on lib/computer.ex
> +  defp minimizing_player(board, mark, depth, alpha, beta) do
I thought to use a hash for the variable, _in a Ruby way_. I'm not really sure about the result and if it's really the Elixir way. I could give a try

2017-04-11 09:03 UTC, fabientownsend commented on lib/computer.ex
> +    Enum.take_random([0, 2, 4, 6, 8], 1) |> Enum.at(0)
👍

2017-04-11 09:05 UTC, felipesere commented on lib/computer.ex
> +  defp minimizing_player(board, mark, depth, alpha, beta) do
I put the comment here, but I don't mean the actual signature... the duplication between `minimizing_player` and `maximizing_player` is what I'd prefer to see reduced

2017-04-11 09:21 UTC, fabientownsend commented on lib/computer.ex
> +  defp minimizing_player(board, mark, depth, alpha, beta) do
Yeah I was on the same page 👍

2017-04-11 17:08 UTC, merged